import type { ConnectorDefinition, ServiceCatalogDefinition } from './types';
import { marriageAppPolicyTier } from './marriage-policy.ts';

const standardCheckpoints: ConnectorDefinition['manualCheckpoints'] = [
  'initial_login',
  'email_or_sms_otp',
  'captcha',
  'age_verification',
  'identity_verification',
  'terms_consent',
  'payment_confirmation',
];

const standardCapabilities: ConnectorDefinition['capabilities'] = [
  'profile',
  'preferences',
  'discovery',
  'like',
  'matches',
  'chat',
  'screenshot',
];

const commonMinimumFields = ['認証方法', '生年月日', '居住地', 'ニックネーム', 'プロフィール写真', '本人・年齢確認'];

function webConnector(
  id: ConnectorDefinition['id'],
  label: string,
  entryUrl: string,
  signupUrl: string,
  options: Partial<Pick<ConnectorDefinition, 'termsUrl' | 'registrationMethods' | 'minimumSetupFields' | 'automationTier' | 'capabilities' | 'limitation' | 'supportStatus' | 'externalAutomationStatus'>> = {},
): ConnectorDefinition {
  const tier = options.automationTier ?? 'beta';
  return {
    id,
    label,
    entryUrl,
    signupUrl,
    termsUrl: options.termsUrl ?? entryUrl,
    capabilities: options.capabilities ?? [...standardCapabilities, 'profile_link'],
    manualCheckpoints: standardCheckpoints,
    webStatus: 'available',
    supportStatus: options.supportStatus ?? 'assisted',
    automationTier: tier,
    automationPolicy: 'manual_handoff',
    externalAutomationStatus: options.externalAutomationStatus ?? 'unverified',
    registrationMethods: options.registrationMethods ?? ['メールアドレス・電話番号（公式画面で選択）'],
    minimumSetupFields: options.minimumSetupFields ?? commonMinimumFields,
    limitation: options.limitation ?? (tier === 'standard'
      ? '公式Web入口と登録情報の準備を優先確認済みです。外部自動操作は許可未確認のため実行せず、公式機能または手動操作へ案内します。'
      : '公式Web入口と登録情報を準備する汎用候補です。外部自動操作は許可未確認のため実行しません。'),
  };
}

const rawConnectorDefinitions: ConnectorDefinition[] = [
  webConnector('pairs', 'Pairs', 'https://pairs.lv/', 'https://pairs.lv/', {
    termsUrl: 'https://pairs.lv/static/termsofservice',
    automationTier: 'standard',
    supportStatus: 'catalog_only',
    registrationMethods: ['LINE', 'Apple', 'Google', '電話番号・メールアドレス'],
    limitation: '公式Web入口と比較情報を提供します。外部自動操作の許可を公式確認できていないため、巡回・いいね・送信は開始しません。',
  }),
  webConnector('with', 'with', 'https://with.is/welcome', 'https://with.is/welcome', {
    termsUrl: 'https://with.is/terms_of_use',
    automationTier: 'standard',
    supportStatus: 'catalog_only',
    externalAutomationStatus: 'prohibited',
    registrationMethods: ['LINE', '電話番号', 'Apple', 'Facebook'],
    limitation: '公式規約が自動投稿・巡回ツール等の使用を禁止しているため、公式Web入口とAI下書き支援だけを提供し、自動操作へは接続しません。',
  }),
  webConnector('omiai', 'Omiai', 'https://www.omiai-jp.com/login', 'https://fb.omiai-jp.com/register.html', {
    termsUrl: 'https://fb.omiai-jp.com/japan/site/kiyaku/',
    automationTier: 'standard',
    supportStatus: 'catalog_only',
    externalAutomationStatus: 'prohibited',
    registrationMethods: ['LINE', '電話番号', 'Apple（対応端末）'],
    limitation: '公式規約が自動投稿・巡回ツール等の使用を禁止しているため、公式Web入口とAI下書き支援だけを提供し、自動操作へは接続しません。',
  }),
  webConnector('marrish', 'marrish', 'https://marrish.com/auth/loginselection', 'https://link.marrish.com/', {
    termsUrl: 'https://marrish.com/auth/userpolicy',
    automationTier: 'standard',
    supportStatus: 'catalog_only',
    externalAutomationStatus: 'prohibited',
    registrationMethods: ['電話番号', 'メール', 'Apple', 'LINE', 'Amazon'],
    limitation: '公式規約が投稿コンテンツの自動収集・解析を禁止しているため、公式Web入口とAI下書き支援だけを提供し、自動操作へは接続しません。',
  }),
  webConnector('youbride', 'youbride', 'https://youbride.jp/auth/login', 'https://youbride.jp/', { termsUrl: 'https://youbride.jp/docs/rule', automationTier: 'standard', registrationMethods: ['メール・ログインID'] }),
  webConnector('bridalnet', 'ブライダルネット', 'https://www.bridalnet.co.jp/login/', 'https://www.bridalnet.co.jp/', { termsUrl: 'https://www.bridalnet.co.jp/rule/', automationTier: 'standard', registrationMethods: ['メールアドレス'] }),
  webConnector('match', 'Match', 'https://jp.match.com/login', 'https://jp.match.com/', { termsUrl: 'https://cp.match.com/ja-jp/resources/Match_Japan_TOU_2024-11-01.pdf', automationTier: 'standard', registrationMethods: ['メールアドレス'] }),
  webConnector('r50time', 'R50Time', 'https://app.r50time.jp/login', 'https://app.r50time.jp/', { termsUrl: 'https://app.r50time.jp/setting/term', automationTier: 'standard', registrationMethods: ['メールアドレス'] }),
  webConnector('tinder', 'Tinder', 'https://tinder.com/app/login', 'https://tinder.com/', {
    termsUrl: 'https://policies.tinder.com/terms/intl/ja/',
    registrationMethods: ['電話番号・連携アカウント'],
    supportStatus: 'catalog_only',
    externalAutomationStatus: 'prohibited',
    limitation: '公式利用条件がロボット等の自動アクセスを禁止しているため、一覧と公式Web入口だけを提供し、自動操作へは接続しません。',
  }),
  webConnector('wakuwaku', 'ワクワクメール', 'https://550909.com/', 'https://550909.com/', { registrationMethods: ['電話番号・メールアドレス'], limitation: '公式Web入口と登録情報を準備する候補です。地域・保守画面へ切り替わる場合や外部自動操作の許可を確認できない状態では実行しません。' }),
  webConnector('ikukuru', 'イククル', 'https://www.194964.com/', 'https://www.194964.com/', { registrationMethods: ['電話番号・メールアドレス'] }),
  webConnector('happymail', 'ハッピーメール', 'https://happymail.co.jp/login/', 'https://happymail.co.jp/', { registrationMethods: ['電話番号・会員番号', 'パスキー'] }),
  webConnector('pcmax', 'PCMAX', 'https://pcmax.jp/pcm/', 'https://pcmax.jp/pcm/file.php?f=registration', { registrationMethods: ['メール・電話番号', 'Google', 'Yahoo! JAPAN'] }),
  webConnector('jmail', 'Jメール', 'https://mintj.com/', 'https://mintj.com/', { registrationMethods: ['電話番号・メールアドレス・会員ID'] }),
  webConnector('asobo', 'ASOBO', 'https://aso-bo.com/login.php', 'https://aso-bo.com/pc/index.php', { registrationMethods: ['電話番号・メールアドレス'] }),
  webConnector('merupara', 'メルパラ', 'https://meru-para.com/msm/login/', 'https://meru-para.com/', { registrationMethods: ['電話番号・メールアドレス・会員ID'] }),
  webConnector('hanakai', '華の会メール', 'https://hana-mail.jp/', 'https://hana-mail.jp/', { registrationMethods: ['電話番号・メールアドレス', 'Google', 'Yahoo!', 'LINE', 'Facebook', 'X', 'Apple'] }),
  webConnector('sugardaddy', 'SugarDaddy', 'https://sugardaddy.jp/login', 'https://sugardaddy.jp/', { registrationMethods: ['メールアドレス・電話番号'] }),
  webConnector('paters', 'paters', 'https://paters.jp/users/sign_in', 'https://paters.jp/welcomes', { registrationMethods: ['電話番号・メールアドレス'] }),
  webConnector('paddy', 'paddy', 'https://www.paddy67.today/', 'https://www.paddy67.today/', { registrationMethods: ['電話番号'] }),
  webConnector('pj', 'PJ', 'https://pj88.jp/users/sign_in', 'https://pj88.jp/', { registrationMethods: ['電話番号・メールアドレス'] }),
  webConnector('mypappy', 'mypappy', 'https://mypappy.jp/signup', 'https://mypappy.jp/signup', { registrationMethods: ['電話番号', 'メールアドレス'] }),
  webConnector('mitsumitsu', 'MITSUMITSU', 'https://lp.mitsumitsu-app.com/', 'https://lp.mitsumitsu-app.com/', { registrationMethods: ['電話番号'] }),
  webConnector('cuddle', 'Cuddle', 'https://www.cuddle-jp.com/signin', 'https://www.cuddle-jp.com/signup', { registrationMethods: ['メールアドレス'] }),
  webConnector('kikonclub', '既婚者クラブ', 'https://kikonclub.com/login', 'https://kikonclub.com/register', { registrationMethods: ['メールアドレス'] }),
  webConnector('anemone', 'Anemone', 'https://app.anemone.blue/', 'https://app.anemone.blue/', { registrationMethods: ['メールアドレス・電話番号'] }),
  webConnector('silk', 'SILK', 'https://app.silk-jp.com/', 'https://app.silk-jp.com/', { registrationMethods: ['メールアドレス・電話番号'] }),
  webConnector('healmate', 'Healmate', 'https://healmate.jp/login', 'https://my.healmate.jp/register', { registrationMethods: ['メールアドレス・電話番号'] }),
  webConnector('marriedgo', 'MarriedGo', 'https://marriedgo.com/', 'https://marriedgo.com/', { registrationMethods: ['メールアドレス'] }),
  webConnector('partners', 'パートナーズ', 'https://www.partner-s.net/signin/entry.php', 'https://www.partner-s.net/signin/entry.php', { registrationMethods: ['メールアドレス'] }),
  webConnector('bachelor-date', 'バチェラーデート', 'https://new.bachelorapp.net/', 'https://new.bachelorapp.net/ma-gy/', { registrationMethods: ['電話番号'] }),
  webConnector('ciel', 'Ciel', 'https://cielmatch.com/howto', 'https://cielmatch.com/howto', { registrationMethods: ['メールアドレス', 'Facebook'] }),
];

export const connectorDefinitions: ConnectorDefinition[] = rawConnectorDefinitions.map((connector) => {
  if (marriageAppPolicyTier(connector.id) !== 'prohibited') return connector;
  return {
    ...connector,
    supportStatus: 'catalog_only',
    automationTier: connector.automationTier,
    externalAutomationStatus: 'prohibited',
    limitation: 'あなたの運用ルールで禁止されています。公式情報の参照だけを提供し、登録準備・接続・外部自動操作には追加しません。',
  };
});

const connectorCategories: Record<string, ServiceCatalogDefinition['category']> = {
  pairs: '恋活',
  with: '恋活',
  omiai: '婚活',
  marrish: '再婚',
  youbride: '婚活',
  bridalnet: '婚活',
  match: '婚活',
  r50time: '年代特化',
  tinder: '恋活',
  wakuwaku: '恋活',
  ikukuru: '恋活',
  happymail: '恋活',
  pcmax: '恋活',
  jmail: '恋活',
  asobo: '恋活',
  merupara: '恋活',
  hanakai: '年代特化',
  sugardaddy: 'デート',
  paters: 'デート',
  paddy: 'デート',
  pj: 'デート',
  mypappy: 'デート',
  mitsumitsu: 'デート',
  cuddle: 'その他',
  kikonclub: 'その他',
  anemone: 'その他',
  silk: '年代特化',
  healmate: 'その他',
  marriedgo: 'その他',
  partners: '婚活',
  'bachelor-date': 'デート',
  ciel: '恋活',
};

const catalogCandidate = (
  id: string,
  label: string,
  entryUrl: string,
  category: ServiceCatalogDefinition['category'],
  options: Partial<Pick<ServiceCatalogDefinition, 'webStatus' | 'availabilityStatus' | 'limitation' | 'termsUrl' | 'externalAutomationStatus'>> = {},
): ServiceCatalogDefinition => ({
  id,
  label,
  entryUrl,
  termsUrl: options.termsUrl,
  category,
  webStatus: options.webStatus ?? 'unverified',
  supportStatus: 'catalog_only',
  automationTier: 'none',
  externalAutomationStatus: options.externalAutomationStatus ?? 'unverified',
  availabilityStatus: options.availabilityStatus ?? 'research',
  registrationMethods: ['公式画面で確認'],
  minimumSetupFields: ['登録方法', '年齢・本人確認', 'プロフィール写真'],
  limitation: options.limitation ?? '掲載候補として追加済みです。現行提供・Web版・利用条件を公式情報で確認中のため、まだ接続対象ではありません。',
});

const additionalServiceCatalog: ServiceCatalogDefinition[] = [
  catalogCandidate('duo', 'Duo', 'https://du0.jp/', '恋活', {
    webStatus: 'available',
    availabilityStatus: 'active',
    limitation: '公式Web入口を確認済みです。登録・規約同意・本人確認の確定は本人が公式画面で行います。',
  }),
  catalogCandidate('r50time', 'R50Time', 'https://r50time.jp/', '年代特化', {
    webStatus: 'available',
    availabilityStatus: 'active',
    limitation: '50歳以上、または50歳以上との出会いを希望する方向け。公式Web入口と要件だけを案内します。',
  }),
  catalogCandidate('hanamel', 'ハナメル', 'https://hanamel.jp/', '年代特化', {
    webStatus: 'available',
    availabilityStatus: 'active',
    limitation: '30歳以上向けの公式Web登録を確認済みです。数字4桁のサービス固有パスワードとして管理します。',
  }),
  catalogCandidate('aikata', 'aikata', 'https://lvs.jp/', '婚活', {
    webStatus: 'available',
    availabilityStatus: 'active',
    limitation: 'Sincerely yoursの後継サービス。公式Web入口を案内し、本人操作で登録します。',
  }),
  catalogCandidate('rere', 'ReRe', 'https://rere.me/lp/rere', '恋活'),
  catalogCandidate('goens', 'Goens', 'https://goen-s.com/', '年代特化', {
    webStatus: 'app_only',
    availabilityStatus: 'active',
    limitation: '50歳以上限定の現行サービスです。会員向けブラウザ版を公式確認できないため、自動操作対象から除外します。',
  }),
  catalogCandidate('tokimeco', 'tokimeco', 'https://tokimeco.me/', '恋活'),
  catalogCandidate('zexy-enmusubi', 'ゼクシィ縁結び', 'https://zexy-enmusubi.net/info/', '婚活', {
    availabilityStatus: 'ended',
    limitation: '公式発表により2026年3月30日でサービス提供を終了しています。接続対象には追加しません。',
  }),
  catalogCandidate('ange', 'アンジュ', 'https://ange.gift/', '年代特化', {
    webStatus: 'available',
    availabilityStatus: 'active',
    termsUrl: 'https://ange.gift/userpolicy/',
    limitation: '30歳以上限定。公式Web登録・ログインを確認済みですが、外部自動操作の許可は未確認のため、公式入口と比較情報だけを提供します。',
  }),
  catalogCandidate('yoitoki', 'YOITOKI', 'https://yoitoki.jp/', '恋活'),
  catalogCandidate('paddy', 'paddy', 'https://www.paddy67.today/', 'デート'),
  catalogCandidate('paters', 'paters', 'https://paters.jp/', 'デート'),
  catalogCandidate('sugardaddy', 'SugarDaddy', 'https://sugardaddy.jp/', 'デート'),
  catalogCandidate('hahhalol', 'ハハロル', 'https://hhll.app/', '年代特化'),
  catalogCandidate('wakuwaku', 'ワクワクメール', 'https://550909.com/', '恋活'),
  catalogCandidate('ikukuru', 'イククル', 'https://194964.com/', '恋活'),
  catalogCandidate('golmachi', 'ゴルマチ', 'https://www.golmachi.com/', 'その他'),
  catalogCandidate('linkle', 'リンクル', 'https://linkleapp.jp/', '恋活'),
  catalogCandidate('mypappy', 'myPappy', 'https://mypappy.jp/', 'デート'),
  catalogCandidate('asobo', 'ASOBO', 'https://aso-bo.com/', '恋活'),
  catalogCandidate('somuri', 'somuri', 'https://somuri.jp/', '年代特化'),
  catalogCandidate('feliz', 'feliz', 'https://feliznet.jp/', '恋活'),
  catalogCandidate('gorgeous', 'GORGEOUS', 'https://thegorgeous.jp/', 'デート'),
  catalogCandidate('wippy', 'WIPPY', 'https://www.wippy.jp/', '恋活'),
  catalogCandidate('scenario', 'scenario', 'https://scenario-app.com/', '恋活'),
  catalogCandidate('pj', 'PJ', 'https://pj88.jp/', 'デート'),
  catalogCandidate('mitsumitsu', 'MITSUMITSU', 'https://lp.mitsumitsu-app.com/', 'デート'),
  catalogCandidate('tantan', 'Tantan', 'https://tantanapp.com/ja', '恋活'),
  catalogCandidate('poiboy', 'Poiboy', 'https://poiboy.jp/', '恋活'),
  catalogCandidate('ravit', 'Ravit', 'https://ravit.jp/', '婚活', {
    webStatus: 'available',
    availabilityStatus: 'active',
    externalAutomationStatus: 'official_native',
    limitation: '公式Web利用と、公式AIエージェントによる相性候補への無料いいねを確認済みです。外部操作は接続せず、サービス内の公式AIを優先します。',
  }),
  catalogCandidate('pcmax', 'PCMAX', 'https://pcmax.jp/', '恋活'),
  catalogCandidate('eveeve', 'イヴイヴ', 'https://eveeve.jp/', '恋活'),
  catalogCandidate('hanakai', '華の会メール', 'https://hana-mail.jp/', '年代特化'),
  catalogCandidate('jmail', 'Jメール', 'https://mintj.com/', '恋活'),
  catalogCandidate('ensports', 'エンスポーツ', 'https://en-sports.jp/', '恋活'),
  catalogCandidate('couplink', 'CoupLink', 'https://couplink.jp/', '恋活', {
    webStatus: 'available',
    availabilityStatus: 'active',
    limitation: '公式Web登録を確認済みです。年齢確認・規約同意・最終送信は本人操作です。',
  }),
  catalogCandidate('laskoi', 'ラス恋', 'https://laskoi.jp/', '年代特化'),
  catalogCandidate('happymail', 'ハッピーメール', 'https://happymail.co.jp/', '恋活'),
  catalogCandidate('tapple', 'タップル', 'https://tapple.me/', '恋活'),
  catalogCandidate('silk', 'Silk', 'https://silk-jp.com/', '年代特化'),
  catalogCandidate('patrona', 'Patrona', 'https://patrona.jp/', 'デート'),
  catalogCandidate('medical-lounge', 'Medical Lounge', 'https://lp.medicallounge.jp/', 'デート'),
  catalogCandidate('koigram', 'Koigram', 'https://koigram.net/', '恋活'),
  catalogCandidate('merupara', 'メルパラ', 'https://meru-para.com/', '恋活'),
  catalogCandidate('dine', 'Dine', 'https://dthree.app/', 'デート', {
    availabilityStatus: 'ended',
    limitation: 'DineブランドはD³へ変更されています。旧サービス名として記録し、現在のD³へ案内します。',
  }),
  catalogCandidate('dthree', 'D³', 'https://dthree.app/', 'デート', {
    webStatus: 'app_only',
    availabilityStatus: 'active',
    limitation: '現行ブランドを確認済みです。アプリでログイン・登録してください。',
  }),
  catalogCandidate('cuddle', 'Cuddle', 'https://www.cuddle-jp.com/', 'その他'),
  catalogCandidate('meetup', 'Meet', 'https://meet-up.jp/', 'その他'),
  catalogCandidate('kikonclub', '既婚者クラブ', 'https://kikonclub.com/', 'その他'),
  catalogCandidate('anemone', 'Anemone', 'https://anemone.blue/', 'その他'),
  catalogCandidate('yahoo-partner', 'Yahoo!パートナー', 'https://app.or.jp/?page_id=110', '恋活', { availabilityStatus: 'ended', limitation: 'サービス終了を確認済みです。比較・移行確認のため履歴として掲載しています。' }),
  catalogCandidate('konkatsu-sapuri', '婚活サプリ', 'https://app.or.jp/?page_id=128', '婚活'),
  catalogCandidate('omicale-live', 'オミカレLive', 'https://app.or.jp/?page_id=130', '婚活'),
  catalogCandidate('carri-kon', 'キャリ婚', 'https://app.or.jp/?page_id=132', '婚活'),
  catalogCandidate('partners', 'パートナーズ', 'https://www.partner-s.net/', '婚活', {
    webStatus: 'available',
    availabilityStatus: 'active',
    limitation: '公式Web登録を確認済みです。パスワードは半角英数字6〜20文字でサービス別に管理します。',
  }),
  catalogCandidate('sincerely-yours', 'Sincerely yours', 'https://lvs.jp/', '婚活', {
    webStatus: 'available',
    availabilityStatus: 'ended',
    limitation: '旧サービス名です。現行のaikataへ移行済みのため、aikataを利用候補として案内します。',
  }),
  catalogCandidate('marimarriage', 'マリマリッジ', 'https://app.or.jp/?page_id=254', '再婚'),
  catalogCandidate('pairs-engage', 'Pairsエンゲージ', 'https://app.or.jp/?page_id=403', '婚活'),
  catalogCandidate('lovesearch', 'ラブサーチ', 'https://app.or.jp/?page_id=552', '恋活'),
  catalogCandidate('ciel', 'Ciel', 'https://app.or.jp/?page_id=257', '恋活'),
  catalogCandidate('comaty', 'Comaty', 'https://app.or.jp/?page_id=268', 'その他'),
  catalogCandidate('ebisuiru', 'EBISUiru', 'https://app.or.jp/?page_id=271', 'その他'),
  catalogCandidate('crossme', 'CROSS ME', 'https://app.or.jp/?page_id=401', '恋活'),
  catalogCandidate('pinnote', 'Pinnote', 'https://app.or.jp/?page_id=527', '恋活'),
  catalogCandidate('talkwave', 'TalkWave', 'https://app.or.jp/?page_id=530', 'その他'),
  catalogCandidate('hop', 'HOP', 'https://app.or.jp/?page_id=549', '恋活'),
  catalogCandidate('pairfull', 'pairfull', 'https://app.or.jp/?page_id=272', '恋活'),
  catalogCandidate('koisapo', 'コイサポ', 'https://app.or.jp/?page_id=273', '恋活'),
  catalogCandidate('wink', 'wink', 'https://app.or.jp/?page_id=277', '恋活'),
  catalogCandidate('cocome', 'CoCome', 'https://app.or.jp/?page_id=290', '恋活'),
  catalogCandidate('animatch', 'Animatch', 'https://app.or.jp/?page_id=291', 'その他'),
  catalogCandidate('aill-goen', 'Aill goen', 'https://app.or.jp/?page_id=294', '恋活'),
  catalogCandidate('knew', 'knew', 'https://app.or.jp/?page_id=309', '婚活'),
  catalogCandidate('bachelor-date', 'バチェラーデート', 'https://app.or.jp/?page_id=310', 'デート'),
  catalogCandidate('teee', 'Teee', 'https://app.or.jp/?page_id=311', 'デート'),
  catalogCandidate('pecoli', 'pecoli', 'https://app.or.jp/?page_id=353', '恋活'),
  catalogCandidate('the-one', 'The One', 'https://app.or.jp/?page_id=362', '婚活'),
  catalogCandidate('konkon', 'KonKon', 'https://app.or.jp/?page_id=364', '婚活'),
  catalogCandidate('ikinari-date', 'いきなりデート', 'https://app.or.jp/?page_id=402', 'デート'),
  catalogCandidate('matchbook', 'Matchbook', 'https://app.or.jp/?page_id=408', '恋活'),
  catalogCandidate('aite-ai', 'aite', 'https://app.or.jp/?page_id=409', '恋活'),
  catalogCandidate('mimi', 'mimi', 'https://app.or.jp/?page_id=410', '恋活'),
  catalogCandidate('kanokare', 'kanokare', 'https://app.or.jp/?page_id=411', '恋活'),
  catalogCandidate('megry', 'Megry', 'https://app.or.jp/?page_id=412', '恋活'),
  catalogCandidate('flagme', 'flagme', 'https://app.or.jp/?page_id=413', '恋活'),
  catalogCandidate('torte', 'Torte', 'https://app.or.jp/?page_id=414', '恋活'),
  catalogCandidate('qunme', 'Qunme', 'https://app.or.jp/?page_id=415', '恋活'),
  catalogCandidate('qoon', 'QooN', 'https://app.or.jp/?page_id=416', '恋活'),
  catalogCandidate('pancy', 'Pancy', 'https://app.or.jp/?page_id=417', '恋活'),
  catalogCandidate('dmm-koikatsu', 'DMM恋活', 'https://app.or.jp/?page_id=420', '恋活'),
  catalogCandidate('metune', 'metune', 'https://app.or.jp/?page_id=421', '恋活'),
  catalogCandidate('dately', 'dately', 'https://app.or.jp/?page_id=422', 'デート'),
  catalogCandidate('match-alarm', 'マッチアラーム', 'https://app.or.jp/?page_id=523', '恋活'),
  catalogCandidate('smatch', 'Smatch', 'https://app.or.jp/?page_id=524', '恋活'),
  catalogCandidate('ferikoi', 'フェリ恋', 'https://app.or.jp/?page_id=526', '恋活'),
  catalogCandidate('aocca', 'aocca', 'https://app.or.jp/?page_id=531', '恋活'),
  catalogCandidate('meple', 'meple', 'https://app.or.jp/?page_id=532', '恋活'),
  catalogCandidate('keypace', 'Keypace', 'https://app.or.jp/?page_id=533', '恋活'),
  catalogCandidate('swish', 'swish', 'https://app.or.jp/?page_id=534', '恋活'),
  catalogCandidate('koyoi', 'Koyoi', 'https://app.or.jp/?page_id=536', 'デート'),
  catalogCandidate('pep', 'pep', 'https://app.or.jp/?page_id=538', '恋活'),
  catalogCandidate('tokyo-enmusubi', 'TOKYO縁結び', 'https://www.futari-story.metro.tokyo.lg.jp/ai-matching/', '婚活', {
    webStatus: 'available',
    availabilityStatus: 'active',
    limitation: '都内在住・在勤・在学、独身証明書、収入証明書、オンライン面談等が必要です。本人のみが登録・利用します。',
  }),
  catalogCandidate('hanabi', 'hanabi', 'https://app.or.jp/?page_id=363', '恋活'),
  catalogCandidate('otakoi', 'オタ恋', 'https://app.or.jp/?page_id=398', '恋活'),
  catalogCandidate('piamy', 'PIAMY', 'https://app.or.jp/?page_id=356', 'その他'),
];

const connectorIds = new Set(connectorDefinitions.map((connector) => connector.id));

export const serviceCatalogDefinitions: ServiceCatalogDefinition[] = [
  ...connectorDefinitions.map((connector) => ({
    id: connector.id,
    label: connector.label,
    entryUrl: connector.entryUrl,
    termsUrl: connector.termsUrl,
    category: connectorCategories[connector.id] ?? 'その他',
    webStatus: connector.webStatus,
    supportStatus: connector.supportStatus,
    automationTier: connector.automationTier,
    externalAutomationStatus: connector.externalAutomationStatus,
    availabilityStatus: 'active' as const,
    registrationMethods: connector.registrationMethods,
    minimumSetupFields: connector.minimumSetupFields,
    limitation: connector.limitation,
  })),
  ...additionalServiceCatalog.filter((candidate) => !connectorIds.has(candidate.id as ConnectorDefinition['id'])),
].sort((a, b) => {
  const policyPriority = { recommended: 0, conditional: 1, unclassified: 2, prohibited: 3 } as const;
  const policy = policyPriority[marriageAppPolicyTier(a.id)] - policyPriority[marriageAppPolicyTier(b.id)];
  const support = Number(b.supportStatus === 'assisted') - Number(a.supportStatus === 'assisted');
  return policy || support || a.label.localeCompare(b.label, 'ja');
});

export function getConnectorDefinition(provider: string) {
  return connectorDefinitions.find((connector) => connector.id === provider) ?? null;
}
